# Generated by Django 2.2 on 2019-05-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان جارت')),
                ('is_active', models.BooleanField(verbose_name='فعال بودن')),
                ('degree', models.CharField(max_length=20, verbose_name='مقطع')),
                ('acceptance_date', models.DateField(verbose_name='تاریخ تصویب')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('course_type', models.IntegerField(max_length=20, verbose_name='نوع درس')),
                ('vahed_nazari', models.IntegerField(verbose_name='تعداد واحد نظری')),
                ('vahed_amali', models.IntegerField(verbose_name='تعداد واحد عملی')),
                ('corequisite_courses', models.ManyToManyField(related_name='_course_corequisite_courses_+', to='myApp.Course', verbose_name='هم\u200cنیاز')),
                ('prerequisite_courses', models.ManyToManyField(related_name='_course_prerequisite_courses_+', to='myApp.Course', verbose_name='پیش\u200cنیاز')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دانشگاه')),
                ('has_associates_degree', models.NullBooleanField(verbose_name='مقطع کاردانی')),
                ('has_bachelors_degree', models.NullBooleanField(verbose_name='مقطع کارشناسی')),
                ('has_masters_degree', models.NullBooleanField(verbose_name='مقطع کارشناسی ارشد')),
                ('has_doctorate_degree', models.NullBooleanField(verbose_name='مقطع دکتری')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(verbose_name='مقطع تحصیلی')),
                ('entrance_year', models.DateField(verbose_name='سال ورود')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Chart', verbose_name='چارت')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='نمره')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Course', verbose_name='درس')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Study', verbose_name='تحصیل')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دانشکده')),
                ('universiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.University', verbose_name='نام دانشگاه')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='course',
            field=models.ManyToManyField(to='myApp.Course'),
        ),
        migrations.AddField(
            model_name='chart',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Faculty', verbose_name='دانشکده'),
        ),
    ]
