# Generated by Django 2.2 on 2019-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190503_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'چارت تحصیلی ', 'verbose_name_plural': 'چارت\u200cهای تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس ', 'verbose_name_plural': 'درس\u200cها '},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'دانشکده ', 'verbose_name_plural': 'دانشکده\u200cها '},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': 'نمره ', 'verbose_name_plural': 'نمره\u200cها '},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'تحصیل ', 'verbose_name_plural': 'تحصیل\u200cها '},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': ' دانشگاه', 'verbose_name_plural': 'دانشگاه\u200cها '},
        ),
    ]
