# Generated by Django 2.2 on 2019-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20190503_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.Course'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان چارت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='corequisite_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_corequisite_courses_+', to='myApp.Course', verbose_name='هم\u200cنیاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_prerequisite_courses_+', to='myApp.Course', verbose_name='پیش\u200cنیاز'),
        ),
    ]
