# Generated by Django 2.2 on 2019-05-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20190507_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(1, 'درس اصلی'), (2, 'درس تخصصی'), (3, 'درس عمومی'), (4, 'درس اختیاری')], verbose_name='نوع درس'),
        ),
    ]
