# Generated by Django 2.2 on 2019-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20190507_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='degree',
            field=models.IntegerField(choices=[(1, 'کاردانی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری')], verbose_name='مقطع تحصیلی'),
        ),
    ]
