# Generated by Django 2.2 on 2019-05-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20190507_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'مقطع تحصیلی ', 'verbose_name_plural': 'مقاطع تحصیلی '},
        ),
    ]
