# Generated by Django 2.2 on 2019-05-06 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0007_auto_20190507_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='corequisite_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_corequisite_courses_+', to='myApp.Course', verbose_name='هم\u200cنیاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_prerequisite_courses_+', to='myApp.Course', verbose_name='پیش\u200cنیاز'),
        ),
    ]
